### ISSUE TITLE
Elliptical border-radius is interpreted as expression.

### ISSUE THREAD

**Issue by tomlokhorst** [dotless/dotless#16]
I have the following CSS:

    button {
      border-radius: 12px / 10px;
    }

When I run this through the dotless compiler, the slash in the [elliptical border-radius](http://www.w3.org/TR/css3-background/#the-border-radius) is seen as an operator.

The previous example gets compiled to:

    button {
      border-radius: 1.2;
    }

Which is not what I wanted.

**Comment by rytmis** [comment]
"Strict math mode" for dotless would be the thing that resolves this one, too.

**Comment by rytmis** [comment]
2e10803 introduces Strict Math for dotless. I've no idea as to how well this compares to less.js, but it's a start.
