### ISSUE TITLE
Difficult to use dotless engine in asp.net outside of handler

### ISSUE THREAD

**Issue by mwrock** [dotless/dotless#179]
First: Excellent library and thanks for your work in providing LESS compilation to the .net community.

I am the project owner of [RequestReduce](https://github.com/mwrock/RequestReduce) and I use dotless to provide LESS compilation of css that is then minified and bundled. I have my own caching, modules, handlers, config and so I like to call the dotless engine directly. This worked great up to 1.2.4 but I just upgraded to 1.3.2 and now I have to resort to some ugly Reflection  in order to get access to the AspNetFactoryContainer. Previously I used `new EngineFactory(config).GetEngine()` but now if I call this where the config's Web property is true, I get a Pandora exception complaining about no IParameterSource. I see that there is now a way to specify that Parameters should be disabled which looks like it would get  around that error, but I do want to use Parameters. So now I use this code:

```
        if (HttpContext.Current == null)
            engine = new EngineFactory(config).GetEngine();
        else
        {
            var dotLessAssembly = Assembly.GetAssembly(typeof (ContainerFactory));
            var factoryType = dotLessAssembly.GetType("dotless.Core.AspNetContainerFactory");
            var fac = (ContainerFactory)(factoryType.InvokeMember("", BindingFlags.CreateInstance, null, null, null));
            var locator = factoryType.InvokeMember("GetContainer", BindingFlags.InvokeMethod, null, fac, new object[] {config});
            engine =
                (ILessEngine)
                (dotLessAssembly.GetType("Microsoft.Practices.ServiceLocation.IServiceLocator").InvokeMember(
                    "GetInstance", BindingFlags.InvokeMethod, null, locator, new object[] {typeof (ILessEngine)}));
        }
```

While this works, it is fragile and aesthetically unattractive (unless you are in to that kind of thing). It would be great if your library could make some of this public or a bit more extensible. There are lots of options here and as long as I dont have to take a dependency on Pandora, it would work for me.

Thanks a bunch and thanks for creating dotless!

**Comment by ForNeVeR** [comment]
You know guys what's interesting? I was able to use this API from F# like that:

```fsharp
open dotless.Core
open dotless.Core.configuration
open System.IO

let path = "C:\\Temp\\less"

let config = DotlessConfiguration()
let locator = ContainerFactory().GetContainer(config)
let engine = (locator.GetService (typeof<ILessEngine>)) :?> ILessEngine
engine.CurrentDirectory <- path

let fileName = Path.Combine (path, "main.less")
let content = File.ReadAllText fileName
let result = engine.TransformToCss (content, fileName)
```

Although an analogous C# program won't compile complaining about inconsistent accessibility:

```csharp
var config = new DotlessConfiguration();
var cf = new ContainerFactory();
var locator = cf.GetContainer(config); // ← error CS0122: 'ContainerFactory.GetContainer(DotlessConfiguration)' is inaccessible due to its protection level
var engine = (ILessEngine)locator.GetService(typeof(ILessEngine));
engine.CurrentDirectory = path;
```
