### ISSUE TITLE
Adding Source file and Line number for each statement in a debug mode

### ISSUE THREAD

**Issue by wezz** [dotless/dotless#226]
I would love a debug mode (for the HTTP handler) where each statement in the compiled CSS contains non-css attributes describing where the LESS statement is located. Ex

ul.quicklinks { -debug-file:"aside.less"; -debug-row:20; }

This would make it a lot easier maintaining and debugging the css.

**Comment by rytmis** [comment]
I believe the "correct" solution for this would be Source Maps (see #302 and its accompanying PR).
