### ISSUE TITLE
Problem running under Medium trust

### ISSUE THREAD

**Issue by gmacut** [dotless/dotless#228]
Problem:
-------------

I've stumbled onto a problem running dotless HttpHandler under Medium trust. Rendering .less files using the handler results in a *System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.*

Steps to reproduce:
---------------------------

In src/dotless.SampleWeb/web.config, under `<system.web>` element add `<trust level="Medium">` and run the application. Loading any *.less files results in a Security Exception.

Proposed fix:
------------------

Line 38 in src/dotless.Core/Importers/Importer.cs seems to be a problem. `System.Environment.CurrentDirectory` apparently isn't allowed under Medium trust. I have tried to return empty string `return ""` instead of `return System.Environment.CurrentDirectory` and it helped, application then runs normally under Medium trust. I suppose I just gave  the rest of the code relative paths instead of absolute ones. I don't know any side affects of my fix, but it works for me, both locally, and on shared hosting under Medium trust.

**Comment by rytmis** [comment]
This seems somewhat related to having a configurable base directory (although it's likely not the only non-full-trust-issue). Might try to work this into 1.5 as well.

**Comment by rytmis** [comment]
Supporting Medium Trust is no longer much of a priority, given that the ASP.NET team basically considers all but Full Trust obsolete for even the current version of MVC, never mind the next one. However, 1d7ac01 does change Importer so that it no longer relies on Environment.CurrentDirectory, so it might work.
