### ISSUE TITLE
dotless.Compiler.exe exits with error code when an empty file is imported

### ISSUE THREAD

**Issue by zzzzBov** [dotless/dotless#237]
If I add a new `.less` file as a placeholder and recompile, I get errors with seemingly unrelated errors, such as:

    .clearfix is undefined on line 97 in file '../less/old.less':
       [96]: {
       [97]:     .clearfix;
             ----^
       [98]: }
      [Done - Failed]

However, if I add `//` (or any other valid non-intrusive content) to the empty file, everything compiles just fine.

**Comment by rytmis** [comment]
Does not seem to reproduce in 1.4.2.

**Comment by rytmis** [comment]
Whoops, yes it does, sorry. Will take a look at this.
