### ISSUE TITLE
missing variables (string interpolation) in @import 

### ISSUE THREAD

**Issue by LaLeLiLeyLu** [dotless/dotless#249]
Missing string interpolation in @import statement.
e.g: 

//importInterpolation.less
@folder: "LessFiles";

@import url("@{folder}/style.less");

//style.less
body{
   color: red;
}

throws FileNotFoundExpection: You are importing a file ending in .less that cannot be found. 
Filename:  "@{folder}/style.less"

tried to solve this problem in my fork, with reading the variables out of _chunk before getting parsed, but I think its not a good idea, its only a workaround and waiting for an good fix.

**Comment by rytmis** [comment]
#353 is a duplicate, but since I noticed that first, I'm closing this one. ;-)
