### ISSUE TITLE
Incorrect URL generated in the compiled CSS

### ISSUE THREAD

**Issue by spierobi** [dotless/dotless#251]
The URL specified for the background attribute in a function in a base less file, is changed by the compiler into a full disk path to that file.

This will cause problems when running the web application because this generated path is invalid at runtime in the context of a web application.

I think the correct behaviour would be to leave the URL path unchanged, as defined in the function.

LESS files content:

general.less

.timelineFaders() {
  &:before {
      background:url("images/faders.png") 0 -15px;
  }
  &:after {
      background:url("images/faders.png") 0 -80px;
  }
}

calendarDay.less

@import "styles/theme_default/general.less";

.calendarDay {
...
 .timelineFaders(); /* calling function defined in general.less file
...
}

Compiled calendarDay.css file:

.calendarDay:before
{
background: url("D:/Projects/web/mijncaress/mijncaress.web/webapps/styles/theme_default/images/faders.png") 0 -15px;
}
.calendarDay:after
{
background: url("D:/Projects/web/mijncaress/mijncaress.web/webapps/styles/theme_default/images/faders.png") 0 -80px;
}

**Comment by rytmis** [comment]
The current behavior seems to mirror Luke's expectations, i.e. the result is styles/theme_default/...
