### ISSUE TITLE
Can you please start writing a changelog.txt

### ISSUE THREAD

**Issue by ltoshev** [dotless/dotless#252]
Hey guys,

can you please start writing a changelog.txt and start adding what is fixed across versions? I saw there is a new version released 5 days ago but I have no idea what is in it?

Something like this will do a great job to make the project more wide spread:

http://www.tinymce.com/develop/changelog/index.php?type=tinymce

**Comment by stesieber** [comment]
I was just looking for release notes, too. Don't know what release notes @Tigraine was pointing to, but I think it would be great to have them just to know what to test after upgrade and/or whether to upgrade or not.

**Comment by rytmis** [comment]
The best I can offer at the moment is the search by milestone feature:

https://github.com/dotless/dotless/milestones?state=closed

I agree, a change log would be nice. I'll consider writing one when I have some free time. :tired_face:
