### ISSUE TITLE
@media mixins not available

### ISSUE THREAD

**Issue by brgrz** [dotless/dotless#255]
If you use Gridpak responsive grid generator, you will see that it wraps .span_X classes with the following:

@media screen and (min-width: 0px) {
  .span_1 {
    .mixin-span(1, @gutter_pc, @gutter_px, @padding, @max_columns);
  }
}

When I try to use the .span_1 class in a file where I imported gridpak.less like so:

div {
 .span_1;
}

it doesn't find the .span_1 class/mixin and doesn't compile. If I remove the media declaration, everything works. What is going on?

**Comment by rytmis** [comment]
This seems to be a case where :extend is the way to go with the current version of the language.
