### ISSUE TITLE
Problem when running from AIR

### ISSUE THREAD

**Issue by petervdn** [dotless/dotless#286]
I'm currently writing a gui for dotless in AIR, and i'm encountering an issue when i run dotless from there. Windows seems to think that the program has stopped responding, and shows me this messagewindow:

http://i.imgur.com/Q2TKjVP.png

This happens when dotless is working fine: output is ok, files are being parsed, it keeps running perfectly when in watch-mode....there doesn't seem to be any problem. Any idea why windows shows me this message?

**Comment by rytmis** [comment]
The commandline watcher feature isn't appropriate for this scenario. If the compiler waits for an enter press to stop watching, it triggers this issue. If it doesn't, there's no way to stop the watcher except to kill it from task manager.
