### ISSUE TITLE
calc() functions are being overwritten

### ISSUE THREAD

**Issue by michaelday** [dotless/dotless#289]
Using dotless for a Windows 8 app, and my css has the following line:

```css
height: calc(100% - 150px);
```

Because of the calc around it, this is something I want to be kept as is so that WinJS can calculate it at runtime. However, dotless is doing math on the inside of the calc, making the final output:

```css
height: calc(-50%);
```

**Comment by AaronLS** [comment]
We switched from another less processor to dotless, and this no longer works:
```width: calc(~"100% - " (@innerScrollOffset));```

expected output:
```width: calc(100% - 209px);```

actual output:
```width: calc(-109%);```

Is there something I am not understanding about why this would not work with dotless?

**Comment by rytmis** [comment]
@AaronLS' example case works in dotless 1.4.2. As for the strict math option, let's consider that for the next feature release.

**Comment by rytmis** [comment]
@AaronLS, I believe the you'll get the result you want if you escape like this:

```less
width: ~"calc(100% - @{innerScrollOffset})";
```

**Comment by rytmis** [comment]
2e10803 introduces Strict Math for dotless. I've no idea as to how well this compares to less.js, but it's a start.
