### ISSUE TITLE
Update to LESS 1.4

### ISSUE THREAD

**Issue by ablohm** [dotless/dotless#298]
I'd really love to see support for the data-uri function, along with the other new features and fixes.

**Comment by rytmis** [comment]
I'm going to close this one, as I can't think of a way to verify full support for the 1.4 language level that would make sense (in terms of effort vs. gain).

However, we've got a bunch of goodies coming up in the 1.5 release:

- @import options 
- Support for CSS lists as mixin arguments
- Variable interpolation in imports and attribute selectors
- Nested ruleset guards
- Strict math mode
- Namespaced imports

Plus a bunch of changes that improve the robustness of mixin resolution and extend.

That said, after 1.5, I'm planning to set the bar a wee bit higher and start working towards a 2.0 release that aims for full parity with the then-current less.js release using the less.js specs as a comparison point.

**Comment by Tigraine** [comment]
+1
