### ISSUE TITLE
@import url(//xxxxx.com?a=b); doesn't work

### ISSUE THREAD

**Issue by napernik** [dotless/dotless#306]
I would like to reference an external css in a schema-agnostic way (http/https)

@import url(//fonts.googleapis.com/css?family=Trocchi);

As a result I'm getting an "Invalid characters in path" exception, as dotLess is trying to parse it as a system file path.

@import url(//xxxxx.com);       // Works
@import url(//xxxxx.com?a=b);        // Doesn't work

**Comment by rytmis** [comment]
Seems to work in the current release.
