### ISSUE TITLE
Pattern-matching mixins not working

### ISSUE THREAD

**Issue by Tommyf** [dotless/dotless#310]
Much like https://github.com/dotless/dotless/issues/127 , this concerns the following part of the spec: http://lesscss.org/#-pattern-matching-and-guard-expressions

The example code in the spec does not compile in dotless.

    .mixin (dark; @color) {
      color: darken(@color, 10%);
    }
    .mixin (light; @color) {
      color: lighten(@color, 10%);
    }
    .mixin (@_; @color) {
      display: block;
    }
    
    @switch: light;
    
    .class {
      .mixin(@switch; #888);
    }

results in:

    Expected ')' but found ' ' on line 1 in file 'C:\<snip>\dotless-v1.3.1.0\test.less':
       []: /beginning of file
      [1]: .mixin (dark; @color) {
           ------------^
      [2]:   color: darken(@color, 10%);
      [Done - Failed]

It seems that https://github.com/dotless/dotless/issues/127 was only related to the guards and not the pattern-matching first parameter.

**Comment by rytmis** [comment]
Semicolons are supported as argument separators in the currently shipping release.
