### ISSUE TITLE
Fade function doesn't work quite as expected.

### ISSUE THREAD

**Issue by zjr-trov** [dotless/dotless#313]
I see the function was added about a year ago, but I thought it was broken for a moment because it doesn't accept the same values as a LESS.js parser.  Where the LESS.js parser would take both a plain number and a percentage, .LESS is only taking a percentage.

Test:
```CSS
background-color: fade(white, 10);
```

Expected output:
```CSS
background-color: rgba(255, 255, 255, 0.1);
```

Actual output:
```CSS
background-color: white;
```

I didn't realize it required a percentage until I was already submitting this issue, so figured it worth going ahead and submitting it.

**Comment by rytmis** [comment]
Based on a quick test, it seems that this:

```less
background-color: fade(white, 10%);
```

as well as:

```less
background-color: fade(white, 0.1);
```

both produce 

```less
background-color: rgba(255, 255, 255, 0.1);
```

So the problem is that dotless doesn't default to having percentage as the unit for fade. Less.js on the other hand defaults to percentages as the unit no matter what you pass in.
