### ISSUE TITLE
QueryString parameter improperly parsed

### ISSUE THREAD

**Issue by bcullman** [dotless/dotless#325]
There seems to be some unnecessary alterations to query string values.

In my html, I am linking to my .less file like so:
```
<link href="style.less?id=E150D96AED789A21AC7C2DD306B45FAAADE49F6EAY" rel="stylesheet" type="text/css" />
```
Inside of style.less is the following declaration:

body {
	background: @white url("background.png?id=@{id}"") no-repeat;
}

The resulting http request looks like this:
```
http://background.png?id=E%20150%20D%2096%20AED%20789%20A%2021%20AC%207%20C%202%20DD%20306%20B%2045%20FAAADE%2049%20F%206%20EAY
```
It appears spaces (%20) characters are being inserted between numbers and letters

**Comment by rytmis** [comment]
Does not reproduce in the current version.
