### ISSUE TITLE
Progress bar pseudo selectors not being output

### ISSUE THREAD

**Issue by grofit** [dotless/dotless#359]
I have some less styles like shown:
```
.as-progress-bar(@color: #32cd32)
{
  .with-rounded-corners(5px);

  &::-webkit-progress-bar-value,
  &::-webkit-progress-value,
  &::-moz-progress-bar
  {
    .with-rounded-corners(6px);
    background-color:@color
  }
}
```

Now if I were to use it like so:

```
progress { .as-progress-bar(); }
```

The output css looks like:

```
progress {
    border-radius: 5px;
}
```

However it does not output the pseudo selectors for the value/bar elements, so is there some bug with this currently?

**Comment by rytmis** [comment]
Works for me in the current master version.
