### ISSUE TITLE
Getting error info when parsing in code

### ISSUE THREAD

**Issue by benwmills** [dotless/dotless#361]
I'm trying to parse some LESS files outside the context of a web application (let's just say a simple C# console app).  I'm trying to use a simple call to Less.Parse(theLessString).  This works when there are no issues with the LESS file, but if there is any kind of problem, then the results are just blank.  I don't see any kind of parsing error.  I know that when I've used dotless within the context of a web application, then LESS parsing errors are thrown as exceptions.  Can anyone point me in the right direction?  I couldn't find anything on the web.  I tried engine.TransformToCss(), but I feel like I'm groping in the dark.

**Comment by hermankan** [comment]
@rytmis, is there any update on this issue? I am facing the same problem and believe it is common when LESS is generated programmatically. Thanks.

**Comment by rytmis** [comment]
Long story short, the current API surface very much looks like your best and only bet is to use `ILessEngine` directly, optionally provide a logger for it, call `TransformToCss`, then look at `ILessEngine.LastTransformationSuccessful`.

Perhaps a LastTransformationError or somesuch might be in order.

**Comment by hermankan** [comment]
Okay, definitely not a showstopper. I have worked that around in the meantime: http://stackoverflow.com/questions/4798154/how-can-i-output-errors-when-using-less-programmatically/30032196#30032196.

**Comment by rytmis** [comment]
Nice workaround. Would having the `ParserException` available as a property property on `LessEngine` help you, though? Because that's something I feel I can pretty easily still include in the upcoming 1.5.0. I don't want to add it to `ILessEngine` yet, because that's the kind of SemVer violation that will actually produce compile-time errors if anyone's implementing `ILessEngine`...

**Comment by hermankan** [comment]
Thanks. Yes, that would be more straightforward, without helper wrappers like mine. By the way, when do you expect the 1.5.0 be released, in particular the NuGet update?

**Comment by rytmis** [comment]
I'm not looking to include anything new in 1.5 at this point, so really I'm just hanging back for any feedback on the beta release -- that, and the two issues you have commented on today.

(In particular, I'm interested in whether dropping the "variable redefines" feature that's a huge divergence from less.js will be a problem.)

**Comment by rytmis** [comment]
That is to say, I'd love to throw it out there as soon as possible, but given that there's been practically zero feedback so far, I'm not feeling entirely confident regarding things like import options. :)

**Comment by rytmis** [comment]
@hermankan check out 1.5.0-beta3 and let me know if it helps you -- `LessEngine.LastTransformationError` should now contain a `ParserException` with the `Zone` as its `ErrorLocation`.

**Comment by hermankan** [comment]
Thanks, @rytmis, it works, so I am removing my `IStylizer` workaround.
