### ISSUE TITLE
The type 'Microsoft.Practices.ServiceLocation.ServiceLocator' exists  in both 'dotless.Core.dll' and  'Microsoft.Practices.ServiceLocation.dll' issue

### ISSUE THREAD

**Issue by javafun** [dotless/dotless#366]
I have a problem when calling getinstance from structuremap container. I got the error message like this 

The type 'Microsoft.Practices.ServiceLocation.ServiceLocator' exists 
in both 'dotless.Core.dll' and 
'Microsoft.Practices.ServiceLocation.dll'.

Did anyone encounter this issue before?

**Comment by rytmis** [comment]
This shouldn't happen at least in the current version. Microsoft.Practices.ServiceLocation.ServiceLocator is ILMerge'd into dotless.core, but it uses the `/internalize` flag, so all the types should be marked internal, and therefore not visible to the outside. If this still reproduces, please reopen and provide a (minimal) test case.
