### ISSUE TITLE
dotless is unable to resolve variables & mixins

### ISSUE THREAD

**Issue by xvdiff** [dotless/dotless#367]
dotless is unable to transform less files containing variables separated in multiple files.
The issue is already described in https://github.com/dotless/dotless/issues/230 and was marked 'Closed' 2 years ago, however I'm still able to reproduce it.

**Create file "main.less"**
```
@import "variables.less";
@import "test.less";
```

**Create file "variables.less"**
```
@blue: #0073b7;
```

**Create file "test.less"**
```
.blue {
       color: @blue;
    }
```

**BundleConfig.cs**
```
bundles.Add(new LessBundle("~/style/common")
    .Include("~/Content/src/main.less"));
```

**Result**
*.blue is undefined on line 2 in file 'test.less'*

**Comment by rytmis** [comment]
Tested the example with 1.4.2 and it worked like you would expect without any configuration switches.

If this issue still persists, please provide me with a command line invocation and a zip file that contains the set of files that exhibit the failure, and I will try to fix it.
