### ISSUE TITLE
Double inserting in the DOM

### ISSUE THREAD

**Issue by julienfroidefond** [dotless/dotless#382]
In my DOM I have : 
<link rel="stylesheet" type="text/css" href='./iso_misc/bsBusUtilsBstrap3Core.less?_v=1.0.11'/>

But when I check in Firefox with Firebug in my network tab, I see 2 queries. 
I am with the Nuget version 1.4.0.0

Thx

**Comment by rytmis** [comment]
I can't think of any way dotless would have anything to do with the DOM, and this issue is missing the actual details. If this issue reoccurs, please open the ticket again with more specifics.
