### ISSUE TITLE
Lazy Loading/Initialisation causes an error.

### ISSUE THREAD

**Issue by igwejk** [dotless/dotless#390]
Here's a valid LESS snippet (an example at http://lesscss.org/features/#variables-feature ):

    .lazy-eval {
        width: @var;
    }

    @var: @a;
    @a: 9%;

It works with the original Less compiler but doesn't work with dotless.

**Comment by rytmis** [comment]
Commit 1ee13c5 changes dotless to behave like less.js. The configuration setting still technically exists (because I don't want to break the programmatic API out of general principle even when I'm changing behavior) but will have no effect.
