### ISSUE TITLE
Multiple dotless sections in web.config on upgrade

### ISSUE THREAD

**Issue by martinsteel** [dotless/dotless#392]
When upgrading dotless through NuGet an additional dotless section is added to the web.config file if any of the attributes have been changed. This causes an internal server error as the web.config file is no longer valid.

**Steps to reproduce**

1. Install dotless 1.4.0 from NuGet
2. Change one of the attributes in web.config from its default (e.g. set cache="false")
3. Update dotless through NuGet to 1.4.1

**Web.config after initial install**
```
<configuration>
  <configSections>
    <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler, dotless.Core" />
  </configSections>
  <dotless minifyCss="false" cache="false" web="false" />
</configuration>
```

**Expected result after update**
```
<configuration>
  <configSections>
    <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler, dotless.Core" />
  </configSections>
  <dotless minifyCss="false" cache="false" web="false" />
</configuration>
```

**Actual result after update**
```
<configuration>
  <configSections>
    <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler, dotless.Core" />
  </configSections>
  <dotless minifyCss="false" cache="false" web="false" />
  <dotless minifyCss="false" cache="true" web="false" />
</configuration>
```

This seems to happen consistently across 5 different web apps with both Visual Studio 2012 & 2013. It doesn't appear to happen if the attributes are left as the defaults.

**Comment by rytmis** [comment]
Meh, still needs some work. When I tested the XDT transform, things went smoothly. Now that I'm actually upgrading dotless in one of my projects, the `<dotless />` tag was incorrectly replaced.
