### ISSUE TITLE
NuGet DLL is in debug mode

### ISSUE THREAD

**Issue by jon-adams** [dotless/dotless#410]
The output from the NuGet package v1.4.1 is a debuggable assembly, instead of being compiled in Release mode.

I assume that wasn't done on purpose, right?

```
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

// Assembly dotless.Core, Version=1.4.1.0, Culture=neutral, PublicKeyToken=96b446c9e63eae34
// MVID: 753b410d-7a6c-44d1-a1a5-78cc5aeab9b5
// References: System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// References: mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// References: System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// References: System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// References: System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// References: System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// References: System.Web.Abstractions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// References: System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

[assembly: AssemblyProduct("dotless v1.4.1.0")]
[assembly: AssemblyInformationalVersion("1.4.1.0")]
[assembly: AssemblyCompany("dotless project")]
[assembly: AllowPartiallyTrustedCallers]
[assembly: AssemblyDescription("Dynamic CSS for .net")]
[assembly: AssemblyCopyright("Copyright © dotless 2010-2012")]
[assembly: AssemblyFileVersion("1.4.1.0")]
[assembly: AssemblyDelaySign(false)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Extension]
[assembly: ComVisible(false)]
[assembly: AssemblyTitle("dotless 1.4.1.0")]
[assembly: AssemblyVersion("1.4.1.0")]
```

**Comment by Tigraine** [comment]
I think this was always the case and nobody bothered to change it since.
Are there any adverse effects of including the debug symbols? Because I think they come in handy when tracking down issues in dotless for users.

**Comment by jon-adams** [comment]
I didn't go through the IL by hand, but I assume this is more of a problem of the DLL being compiled without optimizations, not whether or not PDB symbols are included alongside the DLL.

**Comment by Tigraine** [comment]
I believe that isn't a problem since the level of optimization you get out of your IL code hugely depends how your .NET runtime JIT compiles the dll. I don't think there are any performance implications in the debug/release setting (unlike C or other languages). 

I could be wrong of course - if you have any articles on the topic I'd love to read them.

**Comment by jon-adams** [comment]
According to [Is compiling Release and Debug going to generate different IL code + different machine code?](http://stackoverflow.com/a/13752156/2291):

"Building in Release build turns on the /optimize compile option for the C# compiler. That has a few side-effects, the IL indeed changes but not a great deal." ...
"The most important difference is the [Debuggable] attribute that's emitted for the assembly, its IsJITOptimizerDisabled property is false."

So, yes, it is important so that the JIT does the [optimizations](http://stackoverflow.com/a/4045073/2291) correctly.

**Comment by Tigraine** [comment]
:+1: A thanks a lot - i'll fix that in the build script.

**Comment by jon-adams** [comment]
Confirmed fixed. v1.4.4 does indeed build in release mode and is bundled in the NuGet package as such.

Thanks!
