### ISSUE TITLE
ENOENT error when compiling from path containing a space

### ISSUE THREAD

**Issue by iant-tui** [dotless/dotless#427]
We've got a C# project where dotless isn't working for one of our developers (set as a build action on the .less file and working for other developers using the same project).

From what I can tell the problem is that his Windows username contains a space, so his checkedout less file is at C:\Users\First Last\Documents\GitHub\Project\Project\Website\Content\less\project.less

The output he gets when building includes:
lessc: ENOENT, open 'C:\Users\First Last\Documents\GitHub\Project\Project\Website\Content\less\Last\Documents\GitHub\Project\Project\Website\Content\css\project.css.map'

I believe the problem is because the parameters in monobuild/tasks/build.sh are not quoted, but I'm not sure how to test this out myself or create a patch.

**Comment by rytmis** [comment]
Your error message kind of suggests that you're actually using less.js, not dotless -- the dotless executable would be `dotless.Compiler.exe`, not `lessc`, and `ENOENT` very much smells like something that comes from node.js.

**Comment by iant-tui** [comment]
That's quite possible, I set it up ages ago after trying a few alternatives and it just works for most people now. Thanks for the quick response.

**Comment by iant-tui** [comment]
Yes, I'm using ".Less Msbuild Tasks", which makes a "DotLess" build action available, hence my confusion. For anyone finding this in search results, I've refiled at https://github.com/Jehran/LessMsbuildTasks/issues/6

**Comment by rytmis** [comment]
Thanks for the link, I'm sure it will help someone in the future. :-)
