### ISSUE TITLE
Downloads button on the website take you to wrong place.

### ISSUE THREAD

**Issue by apuchkov** [dotless/dotless#428]
Huge yellow Downloads button on the http://www.dotlesscss.org/ page takes you here: https://github.com/dotless/dotless/downloads with last release from 2012. 

My first though was project abandoned long ago. Then I still decided to try it, got it running, but couldn't not compile Twitter Bootstrap. After some googling I realized I don't have latest version.

Turns out latest version should be pulled from nuget. Shouldn't Download link take you to "https://www.nuget.org/packages/dotless/" instead?

**Comment by rytmis** [comment]
Right you are, thanks for pointing this out. I removed the download link and updated the getting started instructions.

I'll try to cook up a more up to date site in the coming weeks, but I'm prioritizing actual feature development for now. :-)
