### ISSUE TITLE
unit calculations

### ISSUE THREAD

**Issue by spooky** [dotless/dotless#429]
this commit: https://github.com/dotless/dotless/commit/2896c9ae258cfe2fac64509351c5870baae656af
changes behavior between dotless versions.
Previously it was possible to do calculations such as:
10px/16px + 0rem which resulted in 0.625rem
now that the unit stripping is gone, the result is 0.625px.
Is there a way to work around this?

**Comment by spooky** [comment]
nevermind - found the unit() function

**Comment by rytmis** [comment]
I'm glad you found the solution. :)
