### ISSUE TITLE
'multiply' function is processed incorrectly

### ISSUE THREAD

**Issue by SergeyAlexeev** [dotless/dotless#436]
Hello!
I try to parse this LESS string:
    `Less.Parse(".c{color: multiply(white, rgba(96, 96, 96, .1));}")`
in output I have:
    `.c { color: #606060; }`

But if I use JavaScript compiler from `//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.0/less.min.js` I have the another result:
    `.c { color: #efefef; }`

I think, the second result is correct, because I blend normal and transparent colors.

**Comment by rytmis** [comment]
I can't replicate your results -- using this online less.js frontend, I get #606060 from your example as well.

**Comment by SergeyAlexeev** [comment]
This sample  http://jsfiddle.net/gxdkfkk0/3/ demonstrates my result.

**Comment by rytmis** [comment]
All right, thanks. Apparently I was using less.js 1.5 to test this, which explains the discrepancy.
