### ISSUE TITLE
NotSupportedException when using embedded resources

### ISSUE THREAD

**Issue by dutchmega** [dotless/dotless#442]
I'm trying to use embedded resources via dll://assembly, however I'm getting a exception:
System.NotSupportedException: The invoked member is not supported in a dynamic assembly.

This is a result of hitting the following code from dotless/Importer.cs:416, function  LoadFromCurrentDomain:

foreach (var assembly in AppDomain.CurrentDomain
                .GetAssemblies()
                .Where(x => x.Location.EndsWith(assemblyName, StringComparison.InvariantCultureIgnoreCase)))

For dynamic assemblies x.Location will throw a NotSupportedException (see https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location%28v=vs.110%29.aspx) preventing the assembly to be found.

Assembly.GetName().Name might be an alternative.

Environment is ASP.NET 4.5.1 MVC, VS2013.

**Comment by rytmis** [comment]
Thanks for reporting this. Could you provide me with a code example that triggers this problem? I can probably whip one up myself, but if you're already encountering this issue, you can probably do it faster. :)

**Comment by dutchmega** [comment]
Those 3 lines will trigger the exception anywhere in my ASP.NET project :)

**Comment by rytmis** [comment]
OK, so you aren't doing anything in particular to generate the dynamic assembly? Very well, I suppose I can write a test case for that myself. :)

**Comment by rytmis** [comment]
Thanks so much for finding this one. There should be an updated NuGet package (beta3) available within the next 30 minutes or so.
