### ISSUE TITLE
CSS Property unicode-range With U+CODE Causes Failure

### ISSUE THREAD

**Issue by mikejr83** [dotless/dotless#446]
I have a font.less file which contains a bunch of definitions for font-face's like below: 

    @font-face {
      font-family: 'Open Sans';
      font-style: normal;
      font-weight: 400;
      src: url('@{fonts-path}OpenSans400.eot');
      src: local('Open Sans'),
    	  url('@{fonts-path}OpenSans400.eot?#iefix') format('embedded-opentype'),
        url('@{fonts-path}OpenSans400-Cyrillic-ext.woff2?version=@{opensans-version}') format('woff2'),
        url('@{fonts-path}OpenSans400.woff?version=@{opensans-version}') format('woff'),
        url('@{fonts-path}OpenSans400.ttf?version=@{opensans-version}') format('truetype');
      unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
    }

This is the response I get: 

    Cannot apply operator + to the left hand side: U on line 18 in file 'fonts/opensans.less':
     [17]:     url('@{fonts-path}OpenSans400.ttf?version=@{opensans-version}') format('truetype');
     [18]:   unicode-range: U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F;
           ------------------^
     [19]: }
    
    [Done - Failed]

When I compile my less with NodeJS module with my Gulp builds this isn't an issue.

**Comment by mikejr83** [comment]
Reference on the unicode-range from MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-range

**Comment by mikejr83** [comment]
Ok. I should have done more research on this before posting this issue. There is a workaround:

    @font-face {
      font-family: 'Open Sans';
      font-style: normal;
      font-weight: 400;
      src: url('@{fonts-path}OpenSans400.eot');
      src: local('Open Sans'),
    	  url('@{fonts-path}OpenSans400.eot?#iefix') format('embedded-opentype'),
        url('@{fonts-path}OpenSans400-Cyrillic-ext.woff2?version=@{opensans-version}') format('woff2'),
        url('@{fonts-path}OpenSans400.woff?version=@{opensans-version}') format('woff'),
        url('@{fonts-path}OpenSans400.ttf?version=@{opensans-version}') format('truetype');
      unicode-range: ~'U+0460-052F, U+20B4, U+2DE0-2DFF, U+A640-A69F';
    }

Escaping ```unicode-range``` allows the font-face to be output correct.

**Comment by rytmis** [comment]
This does seem like something we should support out of the box given that it works in less.js. Thanks for reporting!

**Comment by rytmis** [comment]
e9d7a11 fixes this.

**Comment by mikejr83** [comment]
Oh nice! Someone did a bad merge on my less file yesterday and went back to the unescaped ranges. I had to look this up! Awesome that it will be native!

**Comment by rytmis** [comment]
I'll try to get a prerelease of 1.5.1 out in a couple of weeks!
