### ISSUE TITLE
Support LESS 2.x.x version

### ISSUE THREAD

**Issue by ducdhm** [dotless/dotless#457]
Hi guys,
When do we have plan to upgrade .less for supporting LESS 2.x.x version?

**Comment by rytmis** [comment]
It's next up on the roadmap. There's quite a bit of work to do to get there, though, and right now I'm both swamped at work and preparing for the holiday season, so I'm not making any promises regarding potential shipping dates yet. In the next month or two I'll probably just ship a point release for bug fixes and get started on the bigger changes later.

Contributions are also welcome, and I'm happy to help people get started and pick tasks. :-)

**Comment by ducdhm** [comment]
@rytmis So can you tell me which version of Less is .less supporting?

**Comment by rytmis** [comment]
That's a bit difficult to answer at the moment. 

In most ways, we're pretty close to 1.5, but I'm sure we've got some features from the 2.x line as well. 1.3 was the last version to track the less language version, and trying to get back on track with the 1.x line of the less language seemed like a waste of effort. 

Instead, the next major version (2.x) of dotless will try to track the then-latest version of the less language (and possibly match the version number as well).

**Comment by rytmis** [comment]
In fact, one of the key tasks on the 2.x roadmap is building a compatibility test suite with less.js -- that would help map out our support of any given feature vs. the canonical implementation.

**Comment by satish-singh** [comment]
@ducdhm Is there any information now, Which version of less using by dotless? Less have v2.7.2 which is current version.

**Comment by rytmis** [comment]
Dotless currently doesn't track any particular language version. It's actually pretty likely that the current implementation will never be 100% on par with less.js -- I'm slowly working towards an entirely new parser and evaluator that would make adding features easier.
