### ISSUE TITLE
Exception in RtlPlugin when  pattern matching mixin is used

### ISSUE THREAD

**Issue by lukeapage** [dotless/dotless#461]
with this code
```
.theme("black") {
}
.theme("black");
```
A Object reference exception occurs on this line...
https://github.com/dotless/dotless/blob/master/src/dotless.Core/Plugins/RtlPlugin.cs#L134

Not sure how that happens..

**Comment by lukeapage** [comment]
Must be a wrong line number.

**Comment by rytmis** [comment]
Reproduced, it looks like we end up with a Rule node with the value "black" but no name -- so the argument of the mixin call gets parsed as a Rule. Not sure if that's what's supposed to happen. Anyway, the exception occurs when we call rule.Name.ToLowerInvariant(), because Name is null.

**Comment by rytmis** [comment]
This is trivially fixed with a (rule.Name ?? "").TLI(); but I'm left wondering as to why the "black" gets parsed as a rule instead of, say, an Expression...

**Comment by rytmis** [comment]
My mistake -- it's not the argument that gets parsed as a Rule, it's the formal parameter of the mixin definition.
