### ISSUE TITLE
Regression: Import inside a mixin is no longer relative

### ISSUE THREAD

**Issue by lukeapage** [dotless/dotless#462]
If the import is inside a mixin, it no longer gets eval'd during the normal process, so the path is not relative...
```
// file.less
@import "subdirectory/sub.less"

// subdirectory/sub.less
.a() {
   @import "sub2.less";
}

// subdirectory/sub2.less
@x: 1;
```

work-around is...

```
// subdirectory/sub.less
.a() {
   @import "subdirectory/sub2.less";
}
```

which works.

**Comment by rytmis** [comment]
I wonder if this is related to #458? I'll take a look at this in the next couple of days, if not sooner.

**Comment by lukeapage** [comment]
I looked into it - basically the NodeUtils expander expands only the direct sub nodes which are Imports, which mean that when you create the using import scope in the import node, it only works for import nodes that are not nested.
With a nested import the import is eval'd outside of the import scope using, so the path is no longer relative.
On less.js we use an import visitor that does a deep scan of parsed nodes and imports any import node  - (https://github.com/less/less.js/blob/master/lib/less/visitors/import-visitor.js).

**Comment by lukeapage** [comment]
I fixed it in a slightly hacky way by making
```
        public static void ExpandNodesDeep<TNode>(Env env, NodeList rules)
                where TNode : Node
        {
            for (var i = 0; i < rules.Count; i++)
            {
                var node = rules[i];

                if (node is TNode)
                {
                    var evaluated = node.Evaluate(env);
                    var nodes = evaluated as IEnumerable<Node>;
                    if (nodes != null)
                    {
                        rules.InsertRange(i + 1, nodes);
                        rules.RemoveAt(i);
                        i--;
                    }
                    else
                    {
                        rules[i] = evaluated;
                    }
                }
                else
                {
                    var ruleset = node as Ruleset;
                    if (ruleset != null && ruleset.Rules != null)
                    {
                        ExpandNodesDeep<TNode>(env, ruleset.Rules);
                    }
                }
            }
        }
```

and calling that from `tree/Import.cs`

Feel free to use that solution or maybe you have visitors which would be more appropriate. (sorry its been so long since I worked on dotless I can't remember much).

**Comment by rytmis** [comment]
Thanks, I'll use your solution if I can't come up with something that fits in with import scopes.

**Comment by lukeapage** [comment]
> Thanks, I'll use your solution if I can't come up with something that fits in with import scopes.

This solution does continue to use import scopes - it just makes sure all imports are processed within a scope rather than only the direct ones.. I'll leave you to look at it anyway.

**Comment by rytmis** [comment]
Yeah, I get that -- what I was going for is that I'm hoping to move all node-related logic to the specific kind of node. That is, I'd like Imports to be able to evaluate themselves fully, likewise MixinCalls and so on. But that's a 2.x project anyway, so this solution probably makes sense for 1.5.1.

**Comment by lukeapage** [comment]
> what I was going for is that I'm hoping to move all node-related logic to the specific kind of node

So e.g. instead of import manager knowing that only things derives from rulesets contain rules, import manager knows a INodeIterable which has a method IterateSubNodes or something like that?

**Comment by rytmis** [comment]
Something to that effect, yes. I've started prototyping the idea in a local branch -- basically, I changed Node.Evaluate to always return an IEnumerable<Node> and added an extension method EvaluateSingle to make the transition a bit easier for the cases where multiple returned nodes don't make sense.

**Comment by rytmis** [comment]
I used your method (with the slight change that I renamed it to RecursiveExpandNodes). I think it's the best way to go about this until the API breaking changes in 2.0.
