### ISSUE TITLE
Property array

### ISSUE THREAD

**Issue by JulianLettner** [dotless/dotless#465]
I am using a [for-each helper](https://github.com/seven-phases-max/less.curious/blob/master/src/for.less) in combination with dotless 1.5.0 and encountered a few problems.
All the examples give the expected output when using: http://lesstester.com

Example from: https://github.com/seven-phases-max/less.curious/blob/master/articles/for-each.md
```less
@import "for.less";

#icon {
    .for(home ok cancel error book); .-each(@name) {
        &-@{name} {
            background-image: url("../images/@{name}.png");
        }
    }
}
```

Output: none (empty file, but other styles are preserved if any), less http listener does not throw anything

Expected output:
```
#icon-home {
  background-image: url("../images/home.png");
}
#icon-ok {
  background-image: url("../images/ok.png");
}
...
```

I suspect that it doesn't recognize the property array.

**Comment by rytmis** [comment]
I think the issue lies within the default() function that isn't implemented. It's easy enough to implement as a function, but I also need to implement the logic that only matches default() guards when nothing else matches...
