### ISSUE TITLE
RTL Plugin - transform translateX

### ISSUE THREAD

**Issue by lukeapage** [dotless/dotless#468]
e.g.

```
transform: translateX(40%);
```
to
```
transform: translateX(-40%);
```

I might look at some of the RtlPlugin issues in my spare time if I get some..

**Comment by lukeapage** [comment]
I worked round this with a mixin, maybe its ott going into the plugin.

**Comment by rytmis** [comment]
I don't have a very good handle on LTR-RTL-issues -- do you think this is a case that should be handled by the plugin? If so, it shouldn't be too hard to make it work.

**Comment by lukeapage** [comment]
I think I'll leave it.
I ported it to js more completely as well, so I'll aim to have them in sync: https://github.com/less/less-plugin-rtl
