### ISSUE TITLE
Breaks when declaration value contains an underscore

### ISSUE THREAD

**Issue by madskristensen** [dotless/dotless#471]
Compiling the following line results in a compiler error:

```css
animation-name: bounce_loadingProgress;
```

When removing the underscore from the value it works fine

**Comment by rytmis** [comment]
Cases like this make me intensely dislike the fact that we parse using regexes instead of a formal grammar... oh well.

I pushed out -alpha2. Give it a whirl.

**Comment by madskristensen** [comment]
We're looking at releasing the LESS parser inside Visual Studio as a NuGet package. We're not ready yet, but will be hopefully later this year. The interfaces won't change much if at all and you can play around with the parser using the assemblies `Microsoft.VisualStudio.Web.Extensions.dll`, `Microsoft.Web.Core.dll` and `Microsoft.CSS.Core.dll` located here:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Editors
```

Thanks for the fix, it works great

**Comment by rytmis** [comment]
Cool, thanks for letting me know!
