### ISSUE TITLE
Add StrictMath suppport for .net 3.5 framework

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [dotless/dotless#474]
Hi,

I have been struggling with calc css3 support as it was not working without strictMath option. However, in one of my projects, i am not able to use .net framework 4.0 or above. Can you provide support or lead me where i should modify your source code?

Additionally, please update your binaries: https://github.com/dotless/dotless/downloads

**Comment by rytmis** [comment]
The latest binaries are available on NuGet.org: https://www.nuget.org/packages/dotless/

I don't have time to test it right now, but from the looks of it, we should support 3.5 across the board: the AspNet, Compiler and Core projects target 3.5. If we've slipped to 4.0 somewhere, please point it out to me -- there's no reason why the core library should be 4.0 specific.

**Comment by oguzhankahyaoglu** [comment]
I examined the issue, i think it is more related with dotless.core than combres library. Anyway, you should support 3.5 framework, too.
