### ISSUE TITLE
StrictMath bugs

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [dotless/dotless#476]
StrictMath mode has some bugs. For example; multipliyng a number with an expression causes errors. I tried many expressions such as wrapping all sub expressions by paranthesis, but none of them worked.
Here  is an example:

@formInputTextDefaultWidth: 300px;
@formInputTextDefaultHeight: 20px;
@formTextareaDefaultWidth: ceil((((@formInputTextDefaultWidth + @formElementHorizontalPadding) + 13px) * 2));

Produces:

Cannot apply operator * to the left hand side: 320px + 13px on line 79 in file '/TheMarmara/Elements/Css/style.less':
 [78]: @formInputTextDefaultHeight: 20px;
 [79]: @formTextareaDefaultWidth: ceil((((@formInputTextDefaultWidth + @formElementHorizontalPadding) + 13px) * 2));
       -------------------------------------------------------------------------------------------------------^
 [80]: @formTextareaDefaultHeight: ceil(@formInputTextDefaultHeight * 3);

**Comment by rytmis** [comment]
Thanks, I'm sure that's not the only one -- strict math doesn't yet have much in the way of test coverage.

**Comment by oguzhankahyaoglu** [comment]
For detailed logging: it evaluates to:
@importantContentLiWidth: floor((1240px - ((1px * 6) + (17px * 6) + (45px * 6))) / 3);

I got that. We want to make use of calc support. We are using both dotless and combres in our development agency. And calc support has dragged me here :) So what is your recommendation that i should do? Wait for your next release? i will start digging in parsers.cs to find the issue by the way..

**Comment by rytmis** [comment]
If you have the time and inclination to get the expression parsing fixed, then please, send a PR with the test and fix. If not, you will have to wait until someone else (most likely me) will fix the issue. I can release a new version fairly quickly once the fix is in. :)

**Comment by oguzhankahyaoglu** [comment]
What is the use of CSS3EXPERIMENTAL flag by the way in core? is it related with it? should i debug the project built with that flag ? or without?

**Comment by rytmis** [comment]
It's related to a single feature -- repeating patterns -- that I believe @lukeapage has implemented. I'm not sure if that's relevant in any way, and I've been considering removing it for a while now. You can build without the flag and ignore the other branch.

**Comment by oguzhankahyaoglu** [comment]
I will give up fixing it, it is causing me a lot of troubles because it is deeply connected to one of my shared libraries. Obviously, i have to wait for your next release :) wish you luck

**Comment by oguzhankahyaoglu** [comment]
Dont forget to build it with 3.5 framework by the way :))

**Comment by rytmis** [comment]
I've got a fix for this coming up -- the implementation was buggy in that when evaluating a subexpression of a parenthesized expression, we shouldn't require additional parens. 

Building for 3.5 is proving to be surprisingly difficult. ILMerge seems to produce v4 assemblies no matter what I try. Will keep digging.

**Comment by oguzhankahyaoglu** [comment]
Looking forward to it :+1:

**Comment by rytmis** [comment]
If all goes well, 1.5.2-alpha1 should hit NuGet soon-ish. Could you please give it a spin and see if you can spot more strict math problems? It's not .NET 3.5 yet as I haven't figured out what the issue with ILMerge is, but I'll try to make the final release build work with 3.5 again.

**Comment by oguzhankahyaoglu** [comment]
Okay i will try and give you feedback until tomorrow :)

**Comment by oguzhankahyaoglu** [comment]
This is also fine with alpha2 release. Thanks for your efforts.
