### ISSUE TITLE
Another strictMath issue (minus values)

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [dotless/dotless#478]
Minus values causes problems, such as:
left: -1000px;
is rendered as:
left: - 1000px;
It has a space before the value. I think, it thinks it as a calc process. Browser (tested on chrome) does not recognize "- 1000px" as a valid value.

**Comment by rytmis** [comment]
Thanks, I appreciate the effort that goes into finding these. I'll try to whip up a fix in the next couple of days for you to try out.

**Comment by oguzhankahyaoglu** [comment]
It now works fine, i tested with 1.5.2-alpha2 version.
