### ISSUE TITLE
Mixin resolution fails when there is another closing paren on the same line

### ISSUE THREAD

**Issue by t1l3r** [dotless/dotless#479]
The following code fragment:
```less
#_linearGradient(top, @colorWhite, formatstring('{0} 0%, {1} 100%', @colorWhite, @colorBGDefault)); filter: ~"progid:DXImageTransform.Microsoft.gradient(@{gradientIE})"; /* IE6-9 */
```
generates the compile error:
```batch
No matching definition was found for `#_linearGradient(...
```
If I put the filter statement on a new line the stylesheet compiles without complaint.
```less
#_linearGradient(top, @colorWhite, formatstring('{0} 0%, {1} 100%', @colorWhite, @colorBGDefault));
filter: ~"progid:DXImageTransform.Microsoft.gradient(@{gradientIE})"; /* IE6-9 */
```

**Comment by rytmis** [comment]
Managed to simplify the repro down to this:

```less
.mixin(@color1, @color2) {
  background-color: @color;
}
.test {
  .mixin(black, white); /* ) */
}
```

Removing the paren from the comments fixes the problem, so my best guess is that when we're matching a mixin call, we match overly greedily -- albeit the error message doesn't quite support that. I'll get to the bottom of this soon.

**Comment by rytmis** [comment]
Interestingly, if the mixin call only has a single argument, the error doesn't reproduce.

**Comment by rytmis** [comment]
Ah, I see why this is the case. It's the combination of a semicolon and a closing paren -- the change I made that allows dotless to recognise semicolon-separated argument lists was faulty.
