### ISSUE TITLE
Error when performing division in shorthand font declaration

### ISSUE THREAD

**Issue by drinkbird** [dotless/dotless#481]
dotless version: 1.5.1 

When I tried to compile [Font Awesome](https://github.com/FortAwesome/Font-Awesome/blob/master/less/core.less) I got a compiler error at the following line:
```less
font: normal normal normal @fa-font-size-base/@fa-line-height-base FontAwesome;
```
indicating that `@fa-font-size-base` is not set. I tried making the division first and assigning the result to the font declaration, and it worked:
```less
@fontsize: @fa-font-size-base/@fa-line-height-base;
font: normal normal normal @fontsize FontAwesome;
```
Could this be an issue of dotless? I tried using [Koala](https://github.com/oklai/koala), and it seems to compile.

**Comment by rytmis** [comment]
Yes, it could, and probably is -- shorthand support for fonts is a recent thing in dotless.

**Comment by drinkbird** [comment]
Thanks, I greatly appreciate the effort (and the impressive response times)

**Comment by rytmis** [comment]
Correction: Shorthand support isn't new, but I recall making changes to it recently. In any case, that wasn't relevant: this is a simple case of not evaluating the variables at the correct point in time.

**Comment by rytmis** [comment]
Try installing 1.5.2-alpha2 (you'll need to use the -Prerelease switch) and see if it fixes things for you. I'll try to get the final 1.5.2 out this weekend.

**Comment by drinkbird** [comment]
That was quick :+1: 
I just tried it, it seems to have another issue now
```
Expected ')' but found ' ' on line 109 in file '../lib/bootstrap/css/carousel.less':
[108]:   &.left {
[109]:     #gradient > .horizontal(@start-color: rgba(0,0,0,.5); @end-color: rgba(0,0,0,.0001));
       --------------------------------------------------------^
[110]:   }
```
There wasn't any problem there before the package update. Could you check it out please?

**Comment by rytmis** [comment]
Hmm, this might be related to the mixin argument change I made yesterday. I'll open up a new issue for this.

**Comment by rytmis** [comment]
I added issue #482 for ensuring that Bootstrap and FA compile with the next release. Will probably take a day or two before I can whip up the fix.

**Comment by drinkbird** [comment]
Thanks a lot! No worries, shorthand operator issue is quite manageable at this point so I could live with 1.5.1 for a few days. Cheers!
