### ISSUE TITLE
RTLPlugin is losing !important on border-width

### ISSUE THREAD

**Issue by sea1jxr** [dotless/dotless#485]
`// bug.less
.selector {
      border-width: 1px 2px 3px 4px !important;
}`

**Running:**
*dotless.compiler.exe -p:Rtl:forceRtlTransform=true bug.less*

**Actual:**
`.selector {
  border-width: 1px 4px 3px 2px;
}`

**Expected:**
`.selector {
  border-width: 1px 4px 3px 2px; !important
}`

**Summary:**
Looks like the borders are correctly adjusted for RTL, but the !important decoration is lost.

**Comment by rytmis** [comment]
Are you running the latest version? I fixed a bunch of these issues in 1.5.1.

**Comment by sea1jxr** [comment]
This is version 1.5.1. I discovered this while upgrading from version 1.3.1.0 to 1.5.1.  So this bug is on 1.5.1. I also noticed several RTL fixes, and I was able to remove workarounds that we had in place. Thank you for those.

-jeff
