### ISSUE TITLE
Unable to use an variable in an @import statement of an imported .less file

### ISSUE THREAD

**Issue by sea1jxr** [dotless/dotless#486]
File a.less
   ` @import "b.less";`

File b.less
    `@foo: "wow";`
   ` @import "@{foo}.less"; `

File wow.less
`.some {}`

**Run:** `dotless.Compiler.exe a.less`

**Actual:**
I get this error
variable @foo is undefined on line 2 in file 'b.less':
  [1]: @foo: "wow";
  [2]: @import "@{foo}.less";
       --------^
  [3]:

**Expected:**
I expected it to compile and have the contents of wow.less

**Comment by sea1jxr** [comment]
I should have mentioned that this is version 1.5.1

**Comment by rytmis** [comment]
Just tested this on dotless 1.5.1 and it didn't reproduce.

**Comment by sea1jxr** [comment]
Interesting, I just recreated the three files and reproduced the error.  How can I best help?

**Comment by rytmis** [comment]
Well, you could start by teaching me to read. I just remembered that I _have_ in fact repro'd this before, but now that I got back around to it, I misread your description... I've spent several hours working on #490 today, so this will have to wait until tomorrow. But now that I'm back in the groove, I'll do my best to get 1.5.2 out with this fixed too, as soon as I have confirmation that the threading issues people have been reporting are  fixed.

**Comment by sea1jxr** [comment]
Sorry the description wasn't more clear.  Thanks for all your hard work.

**Comment by rytmis** [comment]
1.5.2-beta4 should be up on nuget.org in a few minutes, containing a fix for this.
