### ISSUE TITLE
Using class from referenced import as mixin brings in extra styles

### ISSUE THREAD

**Issue by WalkerCodeRanger** [dotless/dotless#490]
I am using dotless 1.5.1.  Unfortunately, I am not set up to test this against less.js and the online compilers I can find don't have a way to use imports.  I found this while trying to reference bootstrap.

There appears to be a bug in which using a class in a referenced less file as a mixin will cause it to include some of the actual styles from the referenced file.  Here are steps to reproduce:

**File: mix-me.less**

	.mix-me
	{
		color: red;
		@media (min-width: 100px)
		{
			color: blue;
		}
		.mix-me-child
		{
			background-color: black;
		}
	}

**File: main.less**

	/* Imports */
	#ns
	{
		@import (reference) "mix-me.less";
	}

	/* Styles */
	.my-class
	{
		#ns.mix-me();
	}

Generating CSS from the main.less file produces:

	/* Imports */

	@media (min-width: 100px) {
	  #ns .mix-me {
		color: blue;
	  }
	}
	#ns .mix-me .mix-me-child {
	  background-color: black;
	}
	/* Styles */

	.my-class {
	  color: red;
	}
	@media (min-width: 100px) {
	  .my-class {
		color: blue;
	  }
	}
	.my-class .mix-me-child {
	  background-color: black;
	}

Everything between `/* Imports */` and `/* Styles */` should not be in the output.  Those are styles from the mix-me.less file.  However, it is only the child styles of the mixed in class that are output.  I know embedding the import in `#ns` is a little strange.  That is not the source of the issue.  In fact, without that, invalid CSS is generated.

**File: no-namespace.less**

	/* Imports */
	@import (reference) "mix-me.less";

	/* Styles */
	.my-class
	{
		.mix-me();
	}

**Outputs:**

	/* Imports */

	@media (min-width: 100px) {
	  .mix-me {
		color: blue;
	  }
	}
	 {
	  background-color: black;
	}
	/* Styles */

	.my-class {
	  color: red;
	}
	@media (min-width: 100px) {
	  .my-class {
		color: blue;
	  }
	}
	.my-class .mix-me-child {
	  background-color: black;
	}

**Comment by rytmis** [comment]
Interesting, on both counts -- thanks for reporting. I'll try to take a look at this soon.

**Comment by rytmis** [comment]
This was decidedly non-trivial to fix. 1.5.2-beta3 should be up on nuget.org with a fix in a few minutes.
