### ISSUE TITLE
Bootstrap 3.3.5 fails while trying to compile with Sublime Text 3

### ISSUE THREAD

**Issue by ccdiego5** [dotless/dotless#491]
Hi, i trying to compile bootstrap 3.3.5 with "LESS-build" package of Sublime Text 3 but fails, here the code:

Expected ')' but found ' ' on line 20 in file 'mixins/image.less':
 [19]: // spelling of `min--moz-device-pixel-ratio` is intentional.
 [20]: .img-retina(@file-1x; @file-2x; @width-1x; @height-1x) {
       --------------------^
 [21]:   background-image: url("@{file-1x}");

**Comment by rytmis** [comment]
It's quite possible that less-build is using an outdated version of dotless. If we're talking about this project:
https://github.com/berfarah/Less-build-sublime

they seem to be using dotless 1.3.1.

**Comment by ccdiego5** [comment]
You can't compile in windows with "dotless", i resolve with this way

http://stackoverflow.com/questions/27507677/sublime-less-build-error-when-compile-bootstrap

**Comment by rytmis** [comment]
Well, that's not strictly true. Bootstrap does compile with dotless, but you have to use the most recent version. :)
