### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by pilotbean** [dotless/dotless#498]
I am using dot less 1.5.2 i am using some existing less that seems to compile as expected in codekit, however using dotless i get a slightly different output. 

width: ((@left-col-width/@page-width)*@percentage-converter);
width:((210px/1008px) * 100%) 
Dotless is outputting 20.8333333px where codekit would make it to 20.8333333% is this a bug or is there something i need to change?

I have found another way to get the same results and that is percentage(@left-col-width/@page-width);

**Comment by rytmis** [comment]
It's rather likely that dotless has a different precedence than less.js for choosing the unit of the result in calculations where the units of the operands are different. I will try to look at this in the near future.
