### ISSUE TITLE
IndexOutOfRangeException when compiling empty @keyframe rulesets

### ISSUE THREAD

**Issue by kingatlas** [dotless/dotless#510]
I'm getting the following exception : 

> An unhandled exception of type 'System.IndexOutOfRangeException' occurred in mscorlib.dll
>    à System.Text.StringBuilder.get_Chars(Int32 index)
>    à dotless.Core.Parser.Infrastructure.Output.TrimLeft(Nullable`1 c) dans F:\Code\dotless\src\dotless.Core\Parser\Infrastructure\Output.cs:ligne 192
>    à dotless.Core.Parser.Infrastructure.Output.Trim() dans F:\Code\dotless\src\dotless.Core\Parser\Infrastructure\Output.cs:ligne 176
>    à dotless.Core.Parser.Tree.Ruleset.AppendRules(Env env) dans F:\Code\dotless\src\dotless.Core\Parser\Tree\Ruleset.cs:ligne 348
>    à dotless.Core.Parser.Tree.Directive.AppendCSS(Env env, Context context) dans F:\Code\dotless\src\dotless.Core\Parser\Tree\Directive.cs:ligne 92
>    à dotless.Core.Parser.Tree.Ruleset.AppendCSS(Env env, Context context) dans F:\Code\dotless\src\dotless.Core\Parser\Tree\Ruleset.cs:ligne 395
>    à dotless.Core.Parser.Tree.Root.AppendCSS(Env env) dans F:\Code\dotless\src\dotless.Core\Parser\Tree\Root.cs:ligne 38
>    à dotless.Core.Parser.Infrastructure.Output.Append(Node node) dans F:\Code\dotless\src\dotless.Core\Parser\Infrastructure\Output.cs:ligne 64
>    à dotless.Core.Parser.Infrastructure.Nodes.Node.ToCSS(Env env) dans F:\Code\dotless\src\dotless.Core\Parser\Infrastructure\Nodes\Node.cs:ligne 119
>    à dotless.Core.LessEngine.TransformToCss(String source, String fileName) dans F:\Code\dotless\src\dotless.Core\Engine\LessEngine.cs:ligne 96
>    à dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName) dans F:\Code\dotless\src\dotless.Core\Engine\ParameterDecorator.cs:ligne 49
>    à dotless.Compiler.FixImportPathDecorator.TransformToCss(String source, String fileName) dans F:\Code\dotless\src\dotless.Compiler\FixImportPathDecorator.cs:ligne 18
>    à dotless.Compiler.Program.CompileImpl(ILessEngine engine, String inputFilePath, String outputFilePath) dans F:\Code\dotless\src\dotless.Compiler\Program.cs:ligne 159
>    à dotless.Compiler.Program.<>c__DisplayClass1_1.<Main>b__1() dans F:\Code\dotless\src\dotless.Compiler\Program.cs:ligne 111
>    à dotless.Compiler.Program.Main(String[] args) dans F:\Code\dotless\src\dotless.Compiler\Program.cs:ligne 115
>    à System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
>    à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>    à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    à System.Threading.ThreadHelper.ThreadStart()

It is occuring when compiling empty directives like the following:

```
@-webkit-keyframes moveFromTop {
    from {
    }

    to {
    }
}
```

The bug is not occuring for other empty rulesets or empty @media queries.

**Comment by Tigraine** [comment]
Damn I missed this. Thanks for the PR!
@rytmis I'll merge this.

**Comment by Tigraine** [comment]
Merged.
