### ISSUE TITLE
[Feature Proposal] Compile to CSS, Keep Variables

### ISSUE THREAD

**Issue by RandyBuchholz** [dotless/dotless#518]
### Background
I'm working on a project where I am dynamically constructing css in my cshtml pages.
Razor allows you to "substitute" with variables:
```
@{
    var widthvar = "10px";
}
<style>
    .element-width { width: @widthvar; }
</style>
```
This provides a lot of flexibility and can minimize the complexity and number of stylesheets.

### Proposed
It would be nice to have the option to compile LESS into (invalid) CSS that retains the LESS variables. This way they can be resolved at compile/run time, even based on runtime values.

```
@{
    var backgroundColor = ViewData["backgroundColor"] as string;
}
<style>
   .coloredBox { height: 20px; width: 20px; background-color: @backgroundColor; }
</style>

<div class= .coloredBox >This box uses runtime color.</div>
```
A char in the variable def would let the compiler know which ones to keep, and could even provide a default value. Something like
```
@keepThisVar:~;
@keepThisVarWithDefault:~ 10px;
```

**Comment by herrquark** [comment]
Why not just write ` .coloredBox { background-color: ~"@backgroundColor"; }`? Which will compile to ` .coloredBox { background-color: @backgroundColor; }`

**Comment by RandyBuchholz** [comment]
@herrquark, that works perfectly! I didn't know about the ~. Funny, I randomly picked that symbol for my example.
