### ISSUE TITLE
compiler fail on less compiling dotles umbraco

### ISSUE THREAD

**Issue by EsmeraldiBejolli** [dotless/dotless#527]
error message

Expected '}' but found '{' on line 44 in file 'mixins.less':
 [43]:   @property: extract(@properties, @i);
 [44]:   @{arguments}: red;
       --^
 [45]:  

code:

```
@colors: @theme-1-chery, @theme-2-chery, @theme-3-chery;
@names: theme-1, theme-2, theme-3;
@length: length(@names);

.build-theme-property(@properties;@value;@i) when (@i > 0) {
    .build-theme-property(@properties;@value;(@i - 1));
  @property: extract(@properties, @i);
  @{property}: @value;
}

.build-theme(@names;@colors;@index;@properties;@prop-num ) when (@index > 0) {
  .build-theme(@names;@colors;(@index - 1);@properties;@prop-num); // decrement.    

    @name: extract(@names, @index);
    @color: extract(@colors, @index);
    body.@{name} &{
      .build-theme-property(@properties; @color; @prop-num);  
    }
}
```

I can figure out if this error message or feature issue because it works when i compile it with winless compiler

Please hep on my project i have show stopper issue causes by dotless

**Comment by rytmis** [comment]
I think the winless compiler uses less.js, which is the reference implementation, so this is probably a missing feature or a bug in dotless.

Can you post a complete minimal example I could try this out with?

**Comment by EsmeraldiBejolli** [comment]
**declare mixin ``**
@colors: @theme-1-chery, @theme-2-chery, @theme-3-chery;
@names: theme-1, theme-2, theme-3;
@length: length(@names);

.build-theme-property(@properties;@value;@i) when (@i > 0) {
    .build-theme-property(@properties;@value;(@i - 1));
  @property: extract(@properties, @i);
  @{property}: @value;
}

.build-theme(@names;@colors;@index;@properties;@prop-num ) when (@index > 0) {
  .build-theme(@names;@colors;(@index - 1);@properties;@prop-num); // decrement.    

    @name: extract(@names, @index);
    @color: extract(@colors, @index);
    body.@{name} &{
      .build-theme-property(@properties; @color; @prop-num);  
    }
}

Usage
`div {
  .build-theme(@names; @colors; @length; color; 1);
}`

expected result 

body.theme-1 div {
  color: blue;
}
body.theme-2 div {
  color: red;
}
body.theme-3 div {
  color: #333333;
}

**Comment by rytmis** [comment]
Ah. Looks like we don't handle variable interpolation in property names -- a much simpler test case fails in the exact same way. Let me think this over for a moment.

**Comment by EsmeraldiBejolli** [comment]
ok thanks 
I'm looking forward for your reply.
LG

**Comment by rytmis** [comment]
I need to run a test and do a couple of other things, but after that, we should have 1.5.3-beta1 up on nuget.org.

**Comment by rytmis** [comment]
So yeah, it took a while because I've entirely forgotten how my AppVeyor setup actually works. Anyway, the nuget is up now, so feel free to test it out:

http://www.nuget.org/packages/dotless/1.5.3-beta1

It's still a prerelease, but if nothing seems to blow up in the next few days, I think I'm going to pull the trigger and release it as 1.5.3.

**Comment by EsmeraldiBejolli** [comment]
Hi @rytmis thank you very much I have test it and there are some little bugs 
` @property: extract(@properties, @i);` 
error : function does not work correctly when there is only one properties 

but anyway thanx
LG
Esmeraldi
