### ISSUE TITLE
We sometimes get a NullReferenceException without a particular reason

### ISSUE THREAD

**Issue by nagilum** [dotless/dotless#528]
Sometimes when we compile our less files, which haven't changed for a while now, we get a NullReferenceException. If we recycle the app pool then everything is all good, with the same less files.

We have tried to setup a try-catch loop, which tries to compile the same files 5 times, just in case, but if the NullReferenceException strikes, it will strike all those 5 times. We recycle and everything is all good again.

Attached is the stack from when the error hits.

[dotless-nullreferenceexception.txt](https://github.com/dotless/dotless/files/1087338/dotless-nullreferenceexception.txt)

**Comment by rytmis** [comment]
Judging by the stack trace (or rather, the build path), you're running a rather old version of dotless. Which version is it?

**Comment by nagilum** [comment]
1.5.1

**Comment by rytmis** [comment]
Ah, right, the Pandora bits in the stack trace threw me off -- it's a binary dependency, so it has build paths that differ from dotless itself.

It took me a while to track it down, but I remembered a similar issue from before. This looks like a duplicate of #480 -- can you try 1.5.2 and see if that fixes the issue for you?

**Comment by nagilum** [comment]
Thanks. I'll try that. I'll reopen the issue if it doesn't fix it.
