### ISSUE TITLE
Changelog 1.6.0.1

### ISSUE THREAD

**Issue by Sc0tTyXL** [dotless/dotless#543]
Hi there,

I cannot find the 1.6.0.1 release here on GitHub and we have blocked 1.5.2 in our package.config's due to a bug.

What is the changelog for v1.6.0.1 ?

I would like to know if our bug has been fixed or not.

**Comment by twenzel** [comment]
I'm sorry for the missing release tag -> https://github.com/dotless/dotless/releases/tag/1.6.0
Which issue do you have?

**Comment by Sc0tTyXL** [comment]
No problem :)

https://github.com/dotless/dotless/issues/501 is the issue.
Is it safe to assume that changes in 1.5.3 (never released) are included into 1.6.0 ?

**Comment by twenzel** [comment]
Yes, this is included.
