### ISSUE TITLE
Microsoft.Extensions.DependencyInjection dependency

### ISSUE THREAD

**Issue by Sc0tTyXL** [dotless/dotless#545]
Hi there,

It seems that dotLess now depends on Standard 2.0. Is there any way to also support Standard 1.6?
I ask this because in Framework 4.6.x projects, Standard 2.0 gets you in binding redirect hell.

For the time being we have reverted back to 1.5.1

**Comment by twenzel** [comment]
@Sc0tTyXL please provide any description.

**Comment by twenzel** [comment]
Hi,

Should there a support for netstandard 1.6 for dotless.Core or dotless.AspNetHandler ?
Or is it also possible for you when we support .NET Framwork 4.5?

**Comment by Sc0tTyXL** [comment]
Targeting 4.6 or 4.5, should be fine. 

None of our applications are NET Standard or Core applications, they are all 4.6.C applications.

**Comment by twenzel** [comment]
But when your applications are using .NET 4.6.1 then it's "automatically" [.NET Standard 2.0 compliant](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
The current version of dotless supports .NET 4.6.1.

**Comment by Sc0tTyXL** [comment]
True but adding NET Standard 2.0 to a NET Framework project throws you into a binding redirect hell.
For instance: https://github.com/dotnet/corefx/issues/22781

**Comment by Leftyx** [comment]
I agree with @Sc0tTyXL . Tried to update package to version 1.6.4 from 1.5.2 and it broken everything in one of our ASP.NET MVC app targeting .Net Framework 4.6.2.

**Comment by twenzel** [comment]
Fixed with 1.6.5.

**Comment by UweKeim** [comment]
I've moved my project from .NET 4.5.2 to .NET 4.7.2. After that, executing this:

```
Update-Package -Reinstall
```

Results in an error:

```
Update-Package : Unable to resolve dependencies. 'Microsoft.Extensions.DependencyInjection 1.1.1' is not compatible with 'dotless.Core 1.6.7 constraint: Microsoft.Extensions.DependencyInjection (>= 2.1.1)'.
```

Is this related to this ticket, or a new one?

**Comment by UweKeim** [comment]
Sorry, after updating "Microsoft.Extensions.DependencyInjection" to version 2.2.2, dotless installs correctly.

**Comment by RajaduraiAz** [comment]
@UweKeim I am getting below error while installing in net471

> Could not install package 'Microsoft.Extensions.DependencyInjection.Abstractions 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author
