### ISSUE TITLE
"Could not install package 'dotless.Core 1.6.2'"

### ISSUE THREAD

**Issue by UweKeim** [dotless/dotless#547]
Today, NuGet suggested an update from 1.5.3-beta1 to 1.6.2.

When trying to update, the following error message appears:

> Could not install package 'dotless.Core 1.6.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any idea how/whether to fix this?

**Comment by twenzel** [comment]
Hi Uwe,

sorry that you get into this problem. The version beginning from 1.6.x only supports .Net Standard 2.0 compatible frameworks, So these are ,NET Framework 4.6.1+ and .NET Core 2 and Mono 5.4.

Either you stick with version 1.5.3 or you upgrade you application/library to use .NET Framework 4.6.1 or higher or convert to .NETStandard/Core 2.0.
If you are currently targeting .NET 4.5.2 it should be a very smooth upgrade to 4.6.1.

**Comment by UweKeim** [comment]
Thanks, I'm putting a `allowedVersions` constraint in my packages.config.
