### ISSUE TITLE
dotless.Core.configuration.WebConfigurationLoader error

### ISSUE THREAD

**Issue by synthieat** [dotless/dotless#548]
Dear all, 

I get the following error message after updating from 1.5.3 to 1.6.2 in VS2017.
Maybe you are able to give me any tip.

German:
Der Typ "dotless.Core.configuration.WebConfigConfigurationLoader" in der Assembly "dotless.Core, Version=1.6.2.0, Culture=neutral, PublicKeyToken=96b446c9e63eae34" konnte nicht geladen werden. 

English
The type "dotless.Core.configuration.WebConfigConfigurationLoader" of the assembly "dotless.Core, Version=1.6.2.0, Culture=neutral, PublicKeyToken=96b446c9e63eae34" could not be loaded. 

[TypeLoadException: Der Typ "dotless.Core.configuration.WebConfigConfigurationLoader" in der Assembly "dotless.Core, Version=1.6.2.0, Culture=neutral, PublicKeyToken=96b446c9e63eae34" konnte nicht geladen werden.]
   System.Web.Optimization.LessTransform.Process(IEnumerable`1& files) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\LessTransform.cs:142
   System.Web.Optimization.<>c__DisplayClass3_0.<GetFileDependencies>b__1(String s) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:72
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +72
   System.Web.Optimization.DependencyCache.GetFileDependencies(Bundle bundle, String virtualPath, BundleContext context) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:81
   System.Web.Optimization.<>c__DisplayClass1_0.<GetTransientBundleFilesKey>b__0(BundleFile file) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:29
   System.Linq.<SelectManyIterator>d__17`2.MoveNext() +188
   System.Linq.<DistinctIterator>d__64`1.MoveNext() +306
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +87
   System.Linq.WhereEnumerableIterator`1.MoveNext() +170
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +133
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +77
   System.Web.Optimization.DependencyCache.ComposeTransientFilesKey(IEnumerable`1 paths) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:112
   System.Web.Optimization.DependencyCache.GetTransientBundleFilesKey(Bundle bundle, BundleContext context) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:27
   System.Web.Optimization.DynamicBundle.GetCacheKey(BundleContext context) in C:\Users\Scott\Documents\GitHub\scott-xu\System.Web.Optimization.Less\System.Web.Optimization.Less\DynamicBundle.cs:48
   System.Web.Optimization.HttpContextCache.Get(BundleContext context, Bundle bundle) +36
   System.Web.Optimization.Bundle.CacheLookup(BundleContext context) +44
   System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context) +21
   System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath) +166
   System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable`1 assets) +205
   System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths) +35
   System.Web.Optimization.Styles.RenderFormat(String tagFormat, String[] paths) +107
   System.Web.Optimization.Styles.Render(String[] paths) +21
   ASP._Page_Views_Shared__Layout_WithoutMenu_cshtml.Execute() in C:\work\CMC-GPS\BPS\ECPWeb\Views\Shared\_Layout_WithoutMenu.cshtml:17
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +105
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +90
   System.Web.WebPages.<>c__DisplayClass40_0.<RenderPageCore>b__0(TextWriter writer) +232
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +63
   System.Web.WebPages.WebPageBase.PopContext() +237
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +98
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +256
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +291
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__3() +198
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
   System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9748665
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159

**Comment by twenzel** [comment]
Is there a repro/branch of System.Web.Optimization.Less where I can reproduce this error?
Keep in mind that starting with version 1.6 only .NET Standard compatible .NET Frameworks (.NET Core 2, .NET Standard 2.0 Libraries and .NET Framework 4.6.1+) are supported.

**Comment by twenzel** [comment]
@synthieat Is there a branch where I can try to reproduce this error?

**Comment by synthieat** [comment]
hmnn, sorry no. It's a web application with a OAUTH 2.0 configuration and dedicated Authentication Server. Setting up the envirenment is difficult. But, I can allow you to connect via TeamViewer. Please contact me via my E-Mail (horst.schneider (et) Hotmail.com)

**Comment by twenzel** [comment]
Please change the section part in web.config file from
```xml
<configSections>
    <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler,dotless.Core" />
  </configSections>
```
to
```xml
<configSections>
    <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler,dotless.AspNet" />
  </configSections>
```
Detail: The assembly name, containing the section handler, has changed in 1.6.

**Comment by synthieat** [comment]
Well, this unfortunately did not help :-(

**Comment by twenzel** [comment]
Please search in your web.config for `xy,dotless.Core` and replace it with `xy,dotless.AspNet`.

**Comment by synthieat** [comment]
Tried with Version 1.6.3 and changed in web.config

` <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler, dotless.Core" /> `
To
` <section name="dotless" type="dotless.Core.configuration.DotlessConfigurationSectionHandler, dotless.AspNet" /> `

and

` <add name="dotless" path="*.less" verb="GET" type="dotless.Core.LessCssHttpHandler, dotless.Core" resourceType="File" preCondition="" />` to

` <add name="dotless" path="*.less" verb="GET" type="dotless.Core.LessCssHttpHandler, dotless.AspNet" resourceType="File" preCondition="" />`

But, it still does throw the same error message.

**Comment by twenzel** [comment]
Can you tell me where the `WebConfigConfigurationLoader` is used? Maybe another web.config elsewhere?

**Comment by twenzel** [comment]
The `System.Web.Optimization.Less` package should be updated. I've created a pull request so the maintainer can use it and create an updated version.
Alternatively you can use your own or my [fork] (https://github.com/twenzel/System.Web.Optimization.Less/tree/feature/UpdateToNewDotless) and compile the assembly on our own.

**Comment by synthieat** [comment]
ok, fine. I've downloaded the source files of System.Web.Optimization, updated all referenced libraries and finally it works with the latest Version 1.6.4.Thank you so much for your help and you Patience. ;-).

**Comment by petersmm** [comment]
@twenzel @synthieat what is the password to your private, I cannot compile without it???
