### ISSUE TITLE
Switch to System.Drawing for .NET Standard

### ISSUE THREAD

**Issue by twenzel** [dotless/dotless#551]
Please switch to [System.Drawing](https://www.nuget.org/packages/System.Drawing.Common) instead of CoreCompat.System.Drawing for .NETStandard profile.

**Comment by cipchk** [comment]
hi, any update plan?

i get this error in `dotless.Core 1.6.4` version: 

> The type 'GraphicsPath' exists in both 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by cipchk** [comment]
Hi, @twenzel

The problem remains unresolved in [1.6.5](https://www.nuget.org/packages/dotless.Core/1.6.5).

> Dependencies
>
> .NETFramework 4.6.1
> Microsoft.Extensions.DependencyInjection (>= 2.0.0)
>
> .NETStandard 2.0
> **CoreCompat.System.Drawing.v2 (>= 5.2.0-preview1-r131)**
> Microsoft.Extensions.DependencyInjection (>= 2.0.0)

**Comment by twenzel** [comment]
@cipchk This was an issue with the NuGet package. Please try 1.6.6.

**Comment by cipchk** [comment]
@twenzel 

Thanks, now is working in 1.6.6.
