### ISSUE TITLE
Dotless HttpHandler Returns Empty Response

### ISSUE THREAD

**Issue by AceCalhoon** [dotless/dotless#555]
I'm having an issue with DotLess installed in an Asp.Net Web Site project (Kentico 11). My .NET framework version is 4.6.1. DotLess is v1.6.4.

I've set up an HTTPHandler, and when I visit the URL for files with multiple levels of imports, the first visit will work as expected. The second and subsequent attempts return an empty response (until the application pool is reset).

Here's my config:

> `<section name="dotless"	type="dotless.Core.configuration.DotlessConfigurationSectionHandler,dotless.AspNet" />`

> `<add name="less-handler" type="dotless.Core.LessCssHttpHandler,dotless.AspNet" path="*.LESS" verb="*" />`

> `<dotless minifyCss="false" cache="false" web="true" strictMath="false" handleWebCompression="false" />`

I've tried with and without handleWebCompression set to true.

For the files in my ZIP:

* mixins.less -- Always loads.
* D.less -- Loads only on first request.
* C.less -- Always loads (generates an error).
* B.less -- Always loads (generates an error but should not).
* A.less -- Loads only on first request (generates an error but should not).

I suspect the issue is tied to import statements somehow, but it doesn't seem consistent. C.less always loads, despite having an import.

Possibly related: I came across this issue while troubleshooting a case where DotLess was giving me different errors (or sometimes none at all) when compiling a Bootstrap-based set of .less files for another project.

[IssueRepro.zip](https://github.com/dotless/dotless/files/2103752/IssueRepro.zip)

**Comment by twenzel** [comment]
Please try version 1.6.7.

**Comment by slope-taylor** [comment]
New version fixed it for me. Thanks!
